CREATE TABLE `tenants` (`id` varchar(64),`name` varchar(255),`created_at` datetime,PRIMARY KEY (`id`));
CREATE TABLE `api_keys` (`id` varchar(64),`tenant_id` varchar(64),`project_id` varchar(64),`plan_id` varchar(64),`name` varchar(255),`key_hash` varchar(255),`lookup_hash` varchar(255),`display` varchar(32),`scopes` text,`disabled` numeric DEFAULT false,`last_used_at` datetime,`created_at` datetime,PRIMARY KEY (`id`));
CREATE UNIQUE INDEX `idx_api_keys_lookup_hash` ON `api_keys`(`lookup_hash`);
CREATE INDEX `idx_api_keys_tenant_id` ON `api_keys`(`tenant_id`);
CREATE TABLE `api_key_model_accesses` (`api_key_id` varchar(64),`model` varchar(255),`created_at` datetime,PRIMARY KEY (`api_key_id`,`model`));
CREATE TABLE `plans` (`id` varchar(64),`tenant_id` varchar(64),`name` varchar(255),`description` text,`limit_micros` integer DEFAULT 0,`limit_tokens` integer DEFAULT 0,`rpm_limit` integer DEFAULT 0,`tpm_limit` integer DEFAULT 0,`concurrency_limit` integer DEFAULT 0,`period` varchar(32),`alert_pct` integer DEFAULT 0,`hard_cutoff` numeric DEFAULT false,`allowed_models` text,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_plans_tenant_id` ON `plans`(`tenant_id`);
CREATE TABLE `accounts` (`id` varchar(64),`tenant_id` varchar(64),`provider` varchar(128),`label` varchar(255),`auth_kind` varchar(32),`secret_wrapped_dek` text,`secret_ciphertext` text,`token_wrapped_dek` text,`token_ciphertext` text,`refresh_wrapped_dek` text,`refresh_ciphertext` text,`token_expires_at` datetime,`metadata` text,`priority` integer DEFAULT 0,`backoff_level` integer DEFAULT 0,`disabled` numeric DEFAULT false,`cooldown_until` datetime,`proxy_pool_id` varchar(64),`needs_reconnect` numeric DEFAULT false,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_accounts_provider` ON `accounts`(`provider`);
CREATE INDEX `idx_accounts_tenant_id` ON `accounts`(`tenant_id`);
CREATE TABLE `chains` (`id` varchar(64),`tenant_id` varchar(64),`name` varchar(255),`strategy` varchar(32),`fallback_provider` varchar(128),`fallback_model` varchar(255),`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_chains_tenant_id` ON `chains`(`tenant_id`);
CREATE TABLE `chain_steps` (`id` varchar(64),`chain_id` varchar(64),`position` integer,`provider` varchar(128),`model` varchar(255),`created_at` datetime,PRIMARY KEY (`id`),CONSTRAINT `fk_chains_steps` FOREIGN KEY (`chain_id`) REFERENCES `chains`(`id`));
CREATE INDEX `idx_chain_steps_chain_id` ON `chain_steps`(`chain_id`);
CREATE TABLE `usage_records` (`id` varchar(64),`tenant_id` varchar(64),`project_id` varchar(64),`api_key_id` varchar(64),`provider` varchar(128),`model` varchar(255),`account_id` varchar(64),`client` varchar(128),`prompt_tokens` integer,`completion_tokens` integer,`cached_tokens` integer,`cache_write_tokens` integer,`cost_micros` integer,`cache_hit` numeric,`latency_ms` integer,`ttft_ms` integer,`slim_bytes_saved` integer,`slim_tokens_saved` integer,`slim_rules` text,`caveman_active` numeric,`terse_active` numeric,`headroom_tokens_saved` integer,`headroom_bytes_saved` integer,`headroom_active` numeric,`ponytail_active` numeric,`created_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_usage_records_created_at` ON `usage_records`(`created_at`);
CREATE INDEX `idx_usage_records_account_id` ON `usage_records`(`account_id`);
CREATE INDEX `idx_usage_records_model` ON `usage_records`(`model`);
CREATE INDEX `idx_usage_records_provider` ON `usage_records`(`provider`);
CREATE INDEX `idx_usage_records_api_key_id` ON `usage_records`(`api_key_id`);
CREATE INDEX `idx_usage_records_tenant_id` ON `usage_records`(`tenant_id`);
CREATE TABLE `budgets` (`id` varchar(64),`tenant_id` varchar(64),`scope_kind` varchar(32),`scope_id` varchar(64),`limit_micros` integer DEFAULT 0,`limit_tokens` integer DEFAULT 0,`period` varchar(32),`alert_pct` integer DEFAULT 0,`hard_cutoff` numeric DEFAULT false,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_budgets_tenant_id` ON `budgets`(`tenant_id`);
CREATE TABLE `audit_entries` (`id` varchar(64),`tenant_id` varchar(64),`actor` varchar(255),`action` varchar(128),`target` varchar(255),`detail` text,`created_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_audit_entries_tenant_id` ON `audit_entries`(`tenant_id`);
CREATE TABLE `model_cooldowns` (`id` varchar(64),`account_id` varchar(64),`model` varchar(255),`cooldown_until` datetime,`created_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_model_cooldowns_account_id` ON `model_cooldowns`(`account_id`);
CREATE TABLE `chain_rotations` (`chain_id` varchar(64),`last_index` integer,`hit_count` integer,`updated_at` datetime,PRIMARY KEY (`chain_id`));
CREATE TABLE `target_rotations` (`scope_key` varchar(255),`last_index` integer,`hit_count` integer,`updated_at` datetime,PRIMARY KEY (`scope_key`));
CREATE TABLE `account_affinities` (`scope_key` varchar(255),`account_id` varchar(64),`expires_at` datetime,`updated_at` datetime,PRIMARY KEY (`scope_key`));
CREATE TABLE `account_healths` (`id` varchar(64),`tenant_id` varchar(64),`account_id` varchar(64),`provider` varchar(128),`model` varchar(255),`status` varchar(32),`latency_ms` integer,`consecutive_failures` integer,`consecutive_successes` integer,`last_ok_at` datetime,`last_checked_at` datetime,`last_error` text,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_account_healths_account_id` ON `account_healths`(`account_id`);
CREATE INDEX `idx_account_healths_tenant_id` ON `account_healths`(`tenant_id`);
CREATE TABLE `resource_samples` (`id` integer PRIMARY KEY AUTOINCREMENT,`tenant_id` varchar(64),`created_at` datetime,`goroutines` integer,`heap_alloc_bytes` integer,`heap_sys_bytes` integer,`gc_pause_ns` integer,`next_gc_bytes` integer,`num_gc` integer,`proc_cpu_percent` real,`proc_rss_bytes` integer,`proc_threads` integer,`proc_open_f_ds` integer,`host_cpu_percent` real,`host_mem_used_bytes` integer,`host_mem_total_bytes` integer,`host_disk_used_bytes` integer,`host_disk_total_bytes` integer,`host_net_sent_bytes` integer,`host_net_recv_bytes` integer,`host_load1` real,`host_load5` real,`host_load15` real,`inflight_requests` integer);
CREATE INDEX `idx_resource_samples_created_at` ON `resource_samples`(`created_at`);
CREATE INDEX `idx_resource_samples_tenant_id` ON `resource_samples`(`tenant_id`);
CREATE TABLE `guardrail_policies` (`id` varchar(64),`tenant_id` varchar(64),`scope` varchar(32),`scope_id` varchar(64),`name` varchar(255),`enabled` numeric DEFAULT true,`config` text,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_guardrail_policies_tenant_id` ON `guardrail_policies`(`tenant_id`);
CREATE TABLE `guardrail_logs` (`id` varchar(64),`tenant_id` varchar(64),`request_id` varchar(64),`api_key_id` varchar(64),`provider` varchar(128),`model` varchar(255),`chain_id` varchar(64),`detector` varchar(32),`direction` varchar(16),`action` varchar(16),`severity` varchar(16),`reason` text,`findings` text,`created_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_guardrail_logs_created_at` ON `guardrail_logs`(`created_at`);
CREATE INDEX `idx_guardrail_logs_tenant_id` ON `guardrail_logs`(`tenant_id`);
CREATE TABLE `resource_buckets` (`id` integer PRIMARY KEY AUTOINCREMENT,`bucket` integer,`proc_cpu_avg` real,`proc_cpu_max` real,`host_cpu_avg` real,`host_cpu_max` real,`proc_rss_avg` real,`proc_rss_max` integer,`host_mem_used_avg` real,`host_mem_used_max` integer,`goroutines_avg` real,`goroutines_max` integer,`heap_alloc_avg` real,`heap_alloc_max` integer,`net_sent_delta` integer,`net_recv_delta` integer,`gc_pause_avg` real,`gc_pause_max` integer,`inflight_avg` real,`inflight_max` integer);
CREATE TABLE `model_aliases` (`alias` varchar(255),`target` varchar(255),PRIMARY KEY (`alias`));
CREATE TABLE `proxy_pools` (`id` varchar(64),`name` varchar(255),`type` varchar(32),`proxy_url` text,`no_proxy` text,`strict` numeric DEFAULT false,`is_active` numeric DEFAULT true,`test_status` varchar(32),`last_tested` datetime,`last_error` text,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE TABLE `settings` (`key` varchar(255),`value` text,PRIMARY KEY (`key`));
CREATE TABLE `custom_providers` (`id` varchar(64),`tenant_id` varchar(64),`display_name` varchar(255),`alias` varchar(128),`dialect` varchar(32),`base_url` text,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_custom_providers_tenant_id` ON `custom_providers`(`tenant_id`);
CREATE TABLE `custom_models` (`id` varchar(64),`tenant_id` varchar(64),`provider_id` varchar(64),`model_id` varchar(255),`display_name` varchar(255),`kind` varchar(32),`context_window` integer,`input_per_m` real,`output_per_m` real,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX `idx_custom_models_provider_id` ON `custom_models`(`provider_id`);
CREATE INDEX `idx_custom_models_tenant_id` ON `custom_models`(`tenant_id`);
